# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('size', models.FloatField(default=0)),
                ('ext', models.CharField(max_length=10)),
                ('vcodec', models.BooleanField(default=False)),
                ('acodec', models.BooleanField(default=False)),
                ('format_id', models.IntegerField(default=43)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('duration', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('playlist_index', models.IntegerField(default=-1)),
                ('fps', models.IntegerField(default=1)),
                ('thumbnail', models.CharField(max_length=300)),
                ('playlist_id', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Video'),
        ),
    ]
