# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlist_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
