# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180328_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlist_index',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
