# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180328_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='video_id',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='video',
            name='playlist_index',
            field=models.IntegerField(null=True),
        ),
    ]
