# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180328_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
