# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180328_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
