# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180328_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('ncounts', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['-height']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='playlist_id',
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Playlist'),
        ),
    ]
